Fix: reformatted env subs. Resolves #33
abeaugustijn/minishell pull request #34
Opened 2020-09-09 18:45 UTC by VictorTennekes

Fixes issues with multiple env vars chained like `$PWD$HOME$PWD` and exported values.

2020-09-10 10:13 UTC, abeaugustijn requested changes
Looks good

2020-09-10 10:13 UTC, abeaugustijn commented on src/utils/replace_env.c
> +	res = zalloc(sizeof(char) * ft_strlen(src)
Could just be malloc right?

2020-09-10 10:32 UTC, VictorTennekes commented on src/utils/replace_env.c
> +	res = zalloc(sizeof(char) * ft_strlen(src)
Yap, has been changed :smile:

2020-09-11 14:08 UTC, abeaugustijn requested changes
ziet dr prima uit

2020-09-11 14:08 UTC, abeaugustijn commented on src/builtin/builtin_export.c
> +#include <stdio.h>
Waarvoor is deze?

2020-09-11 17:35 UTC, VictorTennekes commented on src/builtin/builtin_export.c
> +#include <stdio.h>
Helemaal nop, slordigheidsfoutje.

2020-09-11 17:36 UTC, VictorTennekes commented on src/builtin/builtin_export.c
> +#include <stdio.h>
Is daar blijven hangen na tests.

2020-09-11 20:26 UTC, abeaugustijn approved these changes
Nice

2020-09-11 20:27 UTC, merged